### ISSUE TITLE
Feature: User can search for public holidays by country

### ISSUE THREAD

**Issue by kakriske** [kakriske/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="403" alt="Screenshot 2023-10-03 at 9 25 40 AM" src="https://github.com/kakriske/ajax-project/assets/142456210/9d05f14c-dff9-48ff-b4dd-4fa165b3b0e5">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Fix HTML/CSS to match wireframe and be desktop and mobile responsive.
- [ ] Create a select input box for user to select by country.
- [ ] Capture value chosen upon form submission.
- [ ] Make an Ajax request to 'https://date.nager.at/api/v3/NextPublicHolidays-with country code
- [ ] Set up the list of country codes
- [ ] Create some sort of DOM creation function - to create an li, with the name of the holiday.
- [ ] Populate a ul with those li's.
- **Clean up code
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
